### PR TITLE
[Fix #38] Use standard progress bar

### LINKED ISSUE #38: Use standard progress bar
in order to reduce project's complexity, just use an existing solution for displaying the progress, ETA etc.

possible alternatives:
* https://progressbar-2.readthedocs.io/en/latest/
* https://pypi.python.org/pypi/tqdm

*UAC*
* visual representation of progress (the actual progress bar)
* percentage finished so far
* ETA to finish
* (optional) processed items / total items
* (optional) time taken so far

### PR DESCRIPTION
**Pull request by s-surineni**
I've used python package progressbar2 for this. 
This bar would appear when movie review are being update to the new site.

### CODE REVIEW

**Comment by s-surineni** [comment]
@StegSchreck Could you please take a look and give your comments?

**Comment by StegSchreck** [comment]
Hey @s-surineni.

Sorry for the delay. I was busy with other things. About your changes, here are my thoughts:

old:
image

new:
image

Pros:
- new: elapsed time
- less self-written code

Cons:
- no prefix with site name (not important though, as this can be seen in the line before)


I like it. Could you please adapt the other places too? Then the self-written progressbar could be deleted. After you did this, I will merge it. 


Thank you!

**Comment by s-surineni** [comment]
@StegSchreck How can I test plex parser. Is it necessary to buy subscription?

**Comment by StegSchreck** [comment]
I will take care of Plex. If you are confident by testing one or two parsers / inserters respectively, that's totally fine. I can take over testing the remaining ones when doing the review.

**Comment by s-surineni** [comment]
This issue came up while I was testing progress bar in base_ratings_parser. 
As listal does not have a custom parser defined it is using parser for super class. But there was an error related to fetching page count. I am doubting this error would come if there is only one one page of ratings. I have added only 3 ratings in Listal

`(env_rats) ╭─ssurinen@ssurinen-linux ~/projects/open_source/RatS  ‹further_changes*› 
╰─$ python transfer_ratings.py --source listal --destination criticker
===== Listal: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 111, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 133, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 138, in parse_data_from_source
    movies = parser.parse()
  File "/home/ssurinen/projects/open_source/RatS/RatS/base/base_ratings_parser.py", line 30, in parse
    self._parse_ratings()
  File "/home/ssurinen/projects/open_source/RatS/RatS/base/base_ratings_parser.py", line 45, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "/home/ssurinen/projects/open_source/RatS/RatS/listal/listal_ratings_parser.py", line 28, in _get_pages_count
    .find('div', class_='pages').find_all('a')[-2].get_text())][0]
IndexError: list index out of range`

**Comment by s-surineni** [comment]
@StegSchreck Thanks for your quick response. Looks like the issue is not fixed yet. Because there is an exception that is being raised. 
I am attaching the screen shot of the exception. 
error

**Comment by StegSchreck** [comment]
@s-surineni, I changed it again. Now it will default to 1, if there are no links in the pagination at all. Thanks for your patience.

**Pull request closed without merging**
