### PR TITLE
Adding version check on startup

### PR DESCRIPTION
**Pull request by anurag-rai**
Fix for #39

### CODE REVIEW

**Comment by anurag-rai** [comment]
@StegSchreck is it wise to split the function into two parts? Since one half of reading the current version is a file read, and reading the latest version is an API call?

**Comment by StegSchreck** [comment]
@anurag-rai sounds good.
One thing I don't get yet: when a user is cloning the repo or pulling the docker image. How does your solution know which is the current version? (How does the version file come back from Travis to the project repo)

**Comment by anurag-rai** [comment]
@StegSchreck yes, that's what I wanted to ask next. Currently, users are sitting without a version file. When Travis reads the tag from git and writes to a version file, that particular version file needs to be pushed to the repository right? So that the users who pull next, will have an updated version file.

Right now, Travis creates a version file but it is stuck inside the build.

**Comment by anurag-rai** [comment]
@StegSchreck I'm putting my thoughts out here:
We can write a python function using subprocess to find tag using git and create the version file.

If the repo is cloned, how will this function be invoked? Invoking it everytime the application is run seems costly. Can we have some sort of init module that is invoked only once?

In the docker scenario, we install git with the image and run the same command like travis from the DockerFile. Also, if we install git, we can use the python function to again use git and create the version file.

In both cases, when do we invoke this python subprocess?

**Comment by StegSchreck** [comment]
Thanks for your thoughts, @anurag-rai!
I like the idea, that the application runs the same code for checking the version if it is in docker or not.
We can't just skip the subprocess call, if the file is already present, as the user might have done a git pull. That would cause a mismatch of the file to the actual local version. 
I think, the subprocess call might have to be done every time the `transfer_ratings.py` is executed. The actual script will run for a few hours (depending on the amount of data i.e. movies to process), so waiting a second for the check to be executed seems not so costly in comparison.
An init module doesn't sound bad either.

**Pull request closed without merging**
